# Generated by Django 5.1 on 2024-08-28 09:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='Температура')),
                ('humidity', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Влажность, %')),
                ('pressure', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(600), django.core.validators.MaxValueValidator(900)], verbose_name='Давление воздуха, мм рт.ст.')),
                ('wind_direction', models.PositiveIntegerField(verbose_name='Направление ветра')),
                ('wind_speed', models.FloatField(verbose_name='Скорость ветра, м/с')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='api.place', verbose_name='Место')),
            ],
        ),
    ]
