version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: app
    command: python manage.py runserver --settings=forum.settings_prod
    volumes:
      - ./forum/:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:7.2.4-alpine3.19
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  celery-beat:
